### ISSUE TITLE
É necessário "Pseudônimo do projeto" ?

### ISSUE THREAD

**Issue by RodrigoDornelles** [aHub-Tech/projects-template#8]
Alguns projetos que usam o template da hub não fizeram a alteração do **pseudônimo**, eu mesmo não entendi como documentar.

### Projetos ###

 * <https://github.com/aHub-Tech/hub-reply-bot>
 * <https://github.com/aHub-Tech/hub-profile-api>

### Comentário relacionado ###

> @vcwild eu não entendi o que colocar em **Pseudônimo do projeto**
> 
> _Originally posted by @RodrigoDornelles in https://github.com/aHub-Tech/hub-reply-bot/issues/11#issuecomment-980636969_

**Comment by vcwild** [comment]
@RodrigoDornelles  realmente não faz sentido usar pseudônimo, dá pra remover isso do template
